[package]
name = "data_structs_rust"
version = "0.1.0"
edition = "2021"
license = "MIT"
readme = "README.md"
rust-version = "1.75"
authors = ["Ifaz Kabir <ifazk@noreply.github.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
